# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: coordinates.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'coordinates.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63oordinates.proto\x12\x0b\x63oordinates\"*\n\x07Point3D\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\"7\n\x0f\x43oordinateArray\x12$\n\x06points\x18\x01 \x03(\x0b\x32\x14.coordinates.Point3D\">\n\x12\x43oordinateResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x17\n\x0fpoints_received\x18\x02 \x01(\x05\x32\x65\n\x11\x43oordinateService\x12P\n\x0fSendCoordinates\x12\x1c.coordinates.CoordinateArray\x1a\x1f.coordinates.CoordinateResponseB&\xaa\x02#AkkaNet.Examples.GrpcServiceExampleb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'coordinates_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002#AkkaNet.Examples.GrpcServiceExample'
  _globals['_POINT3D']._serialized_start=34
  _globals['_POINT3D']._serialized_end=76
  _globals['_COORDINATEARRAY']._serialized_start=78
  _globals['_COORDINATEARRAY']._serialized_end=133
  _globals['_COORDINATERESPONSE']._serialized_start=135
  _globals['_COORDINATERESPONSE']._serialized_end=197
  _globals['_COORDINATESERVICE']._serialized_start=199
  _globals['_COORDINATESERVICE']._serialized_end=300
# @@protoc_insertion_point(module_scope)
