# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/server.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'proto/server.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12proto/server.proto\x12\x04\x63hat\"&\n\rServerSummary\x12\x15\n\rmessage_count\x18\x01 \x01(\x05\"\x9f\x01\n\rClientMessage\x12)\n\x05start\x18\x01 \x01(\x0b\x32\x18.chat.ClientMessageStartH\x00\x12/\n\x08\x63ustomer\x18\x02 \x01(\x0b\x32\x1b.chat.ClientMessageCustomerH\x00\x12\'\n\x04stop\x18\x03 \x01(\x0b\x32\x17.chat.ClientMessageStopH\x00\x42\t\n\x07\x63ontent\"%\n\x12\x43lientMessageStart\x12\x0f\n\x07initial\x18\x01 \x01(\t\"%\n\x15\x43lientMessageCustomer\x12\x0c\n\x04name\x18\x01 \x01(\t\"#\n\x11\x43lientMessageStop\x12\x0e\n\x06reason\x18\x01 \x01(\t2O\n\nChatServer\x12\x41\n\x13HandleCommunication\x12\x13.chat.ClientMessage\x1a\x13.chat.ServerSummary(\x01\x42\x17\xaa\x02\x14\x43hatServerApp.Protosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.server_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\024ChatServerApp.Protos'
  _globals['_SERVERSUMMARY']._serialized_start=28
  _globals['_SERVERSUMMARY']._serialized_end=66
  _globals['_CLIENTMESSAGE']._serialized_start=69
  _globals['_CLIENTMESSAGE']._serialized_end=228
  _globals['_CLIENTMESSAGESTART']._serialized_start=230
  _globals['_CLIENTMESSAGESTART']._serialized_end=267
  _globals['_CLIENTMESSAGECUSTOMER']._serialized_start=269
  _globals['_CLIENTMESSAGECUSTOMER']._serialized_end=306
  _globals['_CLIENTMESSAGESTOP']._serialized_start=308
  _globals['_CLIENTMESSAGESTOP']._serialized_end=343
  _globals['_CHATSERVER']._serialized_start=345
  _globals['_CHATSERVER']._serialized_end=424
# @@protoc_insertion_point(module_scope)
