# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: server.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'server.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cserver.proto\x12\x04\x63hat\"n\n\rClientMessage\x12)\n\x05login\x18\x01 \x01(\x0b\x32\x18.chat.ClientMessageLoginH\x00\x12\'\n\x04\x63hat\x18\x02 \x01(\x0b\x32\x17.chat.ClientMessageChatH\x00\x42\t\n\x07\x63ontent\"=\n\x12\x43lientMessageLogin\x12\x14\n\x0c\x63hat_room_id\x18\x01 \x01(\t\x12\x11\n\tuser_name\x18\x02 \x01(\t\"!\n\x11\x43lientMessageChat\x12\x0c\n\x04text\x18\x01 \x01(\t\"\xed\x01\n\rServerMessage\x12\x38\n\rlogin_success\x18\x01 \x01(\x0b\x32\x1f.chat.ServerMessageLoginSuccessH\x00\x12\x38\n\rlogin_failure\x18\x02 \x01(\x0b\x32\x1f.chat.ServerMessageLoginFailureH\x00\x12\x34\n\x0buser_joined\x18\x03 \x01(\x0b\x32\x1d.chat.ServerMessageUserJoinedH\x00\x12\'\n\x04\x63hat\x18\x04 \x01(\x0b\x32\x17.chat.ServerMessageChatH\x00\x42\t\n\x07\x63ontent\"+\n\x19ServerMessageLoginFailure\x12\x0e\n\x06reason\x18\x01 \x01(\t\"\x1b\n\x19ServerMessageLoginSuccess\",\n\x17ServerMessageUserJoined\x12\x11\n\tuser_name\x18\x01 \x01(\t\"4\n\x11ServerMessageChat\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x11\n\tuser_name\x18\x02 \x01(\t2Q\n\nChatServer\x12\x43\n\x13HandleCommunication\x12\x13.chat.ClientMessage\x1a\x13.chat.ServerMessage(\x01\x30\x01\x42\x17\xaa\x02\x14\x43hatServerApp.Protosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\024ChatServerApp.Protos'
  _globals['_CLIENTMESSAGE']._serialized_start=22
  _globals['_CLIENTMESSAGE']._serialized_end=132
  _globals['_CLIENTMESSAGELOGIN']._serialized_start=134
  _globals['_CLIENTMESSAGELOGIN']._serialized_end=195
  _globals['_CLIENTMESSAGECHAT']._serialized_start=197
  _globals['_CLIENTMESSAGECHAT']._serialized_end=230
  _globals['_SERVERMESSAGE']._serialized_start=233
  _globals['_SERVERMESSAGE']._serialized_end=470
  _globals['_SERVERMESSAGELOGINFAILURE']._serialized_start=472
  _globals['_SERVERMESSAGELOGINFAILURE']._serialized_end=515
  _globals['_SERVERMESSAGELOGINSUCCESS']._serialized_start=517
  _globals['_SERVERMESSAGELOGINSUCCESS']._serialized_end=544
  _globals['_SERVERMESSAGEUSERJOINED']._serialized_start=546
  _globals['_SERVERMESSAGEUSERJOINED']._serialized_end=590
  _globals['_SERVERMESSAGECHAT']._serialized_start=592
  _globals['_SERVERMESSAGECHAT']._serialized_end=644
  _globals['_CHATSERVER']._serialized_start=646
  _globals['_CHATSERVER']._serialized_end=727
# @@protoc_insertion_point(module_scope)
