<Project Sdk="Microsoft.NET.Sdk.Web">
	<Import Project="..\..\Common.props" />

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<UserSecretsId>88c16b92-ad1d-42c6-8200-d0ce0e16fb6f</UserSecretsId>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
		<DockerfileContext>.</DockerfileContext>
	</PropertyGroup>

	<ItemGroup>
		<!--<Protobuf Include="Protos\greet.proto" GrpcServices="Server" />-->
		<Protobuf Include="*/*.proto" GrpcServices="Server" ProtoRoot="Protos" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Akka" Version="1.5.43" />
		<PackageReference Include="Akka.Cluster" Version="1.5.43" />
		<PackageReference Include="Akka.DependencyInjection" Version="1.5.43" />
		<PackageReference Include="Akka.Hosting" Version="1.5.42" />
		<PackageReference Include="Akka.Remote" Version="1.5.43" />
		<PackageReference Include="Grpc.AspNetCore" Version="2.57.0" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.6" />
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1-Preview.1" />
	</ItemGroup>

</Project>